spring.application.name=api

# Database Configuration (Defaults: H2 for local, Env Vars for Docker)
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# JPA Settings (Defaults: H2Dialect, Env Vars for Docker)
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initial Data Seed Configuration (Force execution of data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
