spring.application.name=api

# Database Configuration (Defaults: H2 for local, Env Vars for Docker)
spring.datasource.url=${DB_URL:jdbc:h2:mem:sctec_empreendimentos;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

# JPA Settings (Defaults: H2Dialect, Env Vars for Docker)
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Migrations
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
